service:
  type: LoadBalancer
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: status-port
      port: 15021
      targetPort: 15021
    - name: grpc
      port: 5000
      targetPort: 5000
