version: "3.9"
services:
  aerospike-cluster:
    image: aerospike/aerospike-server-enterprise:7.0.0.5
    container_name: "aerospike-cluster"
    command: --config-file /etc/aerospike/aerospike.conf
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ${PWD}/config:/etc/aerospike
    healthcheck:
#      test: [ "CMD", "asinfo", "-U", "admin", "-P", "admin", "-p", "3000", "-v", "build" ]
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - svc
  aerospike-graph:
    image: aerospike/aerospike-graph-service
    container_name: aerospike-graph
      #    restart: always
    depends_on:
     aerospike-cluster:
       condition: service_healthy
    ports:
      - '8182:8182'
      - '9090:9090'
    environment:
      - aerospike.client.namespace=test
      - aerospike.client.host=aerospike-cluster
      - aerospike.graph.index.vertex.label.enabled=true
    networks:
      - svc
  aerospike-vector-search:
    image: aerospike/aerospike-vector-search:1.0.0
    container_name: "aerospike-vector-search"
    depends_on:
      aerospike-cluster:
        condition: service_healthy
    ports:
     - "5555:5000"
     - "5040:5040"
    networks:
      - svc
    volumes:
      - ${PWD}/config:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aerospike-vector-search:5040/manage/rest/v1"]
      interval: 30s
      timeout: 20s
      retries: 3

#  aerospike-client:
#    image: aerospike/aerospike-tools:10.2.1
#    container_name: "aerospike-client"
#    depends_on:
#      aerospike-cluster:
#        condition: service_healthy
#    command: [
#      "asadm",
#      "-U", "admin",
#      "-P", "admin",
#      "-e", 'enable; manage acl create user tester password psw roles truncate sindex-admin user-admin data-admin read-write read write read-write-udf sys-admin udf-admin',
#      "--no-config-file",
#      "-h", "aerospike-cluster",
#      "-p", "3000"
#    ]
#    networks:
#      - svc

networks:
  svc:
    name: svc


