services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    # ports:
    #   - "3000:3000"
    networks:
      - avs-demo
    volumes:
      - ./quote-semantic-search/container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
  avs:
    image: aerospike/aerospike-vector-search:0.11.1
    # ports:
    #   - "5002:5002"
    networks:
      - avs-demo
    volumes:
      - ./quote-semantic-search/container-volumes/avs/etc/aerospike-vector-search:/etc/aerospike-proximus
  app:
    build:
      context: .
      dockerfile: Dockerfile-quote-search
    develop:
      watch:
        - path: ./quote-search
          action: rebuild
    image: quote-search
    ports:
      - "8080:8080"
    networks:
      - avs-demo
    volumes:
      - ./quote-semantic-search/container-volumes/quote-search/data:/container-volumes/quote-search/data
    environment:
      AVS_HOST: avs
      AVS_PORT: "5000"
      APP_NUM_QUOTES: "5000"
      GRPC_DNS_RESOLVER: native

networks:
  avs-demo: {}
