services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    ports:
      - "3000:3000"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
  proximus:
    image: aerospike/aerospike-proximus:0.3.1
    ports:
      - "5002:5002"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/proximus/etc/aerospike-proximus:/etc/aerospike-proximus
  app:
    image: quote-search
    ports:
      - "8080:8080"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/quote-search/data:/container-volumes/quote-search/data
      # ./usr/local/lib/python3.10/dist-packages/sentence_transformers
    environment:
      - PROXIMUS_HOST=proximus
      - PROXIMUS_PORT=5002
      - APP_NUM_QUOTES=5000
      - GRPC_DNS_RESOLVER=native

  
networks:
  proximus-demo: {}

volumes:
 app_data: {}