apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  size: 3
  image: aerospike/aerospike-server-enterprise:7.0.0.0
  storage:
    filesystemVolumePolicy:
      initMethod: deleteFiles
      cascadeDelete: true
    blockVolumePolicy:
      cascadeDelete: true
    volumes:
      - name: workdir
        aerospike:
          path: /opt/aerospike
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Filesystem
            size: 1Gi
      - name: avs-meta
        aerospike:
          path: /avs-meta/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 2Gi
      - name: avs-index
        aerospike:
          path: /avs-index/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 20Gi
      - name: avs-data
        aerospike:
          path: /avs-data/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 20Gi
      - name: ns
        aerospike:
          path: /test/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 1Gi
      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret
      - name: aerospike-tls-config
        source:
          secret:
            secretName: aerospike-tls
        aerospike:
          path: /etc/aerospike/ssl


  podSpec:
    sidecars:
    - name: aerospike-prometheus-exporter
      image: aerospike/aerospike-prometheus-exporter:v1.9.0
      ports:
        - containerPort: 9145
          name: exporter
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: aerospike.com/node-pool
              operator: In
              values:
              - "default-rack"
    multiPodPerHost: false

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin
      - name: tester
        secretName: auth-secret
        roles:
          - truncate
          - sindex-admin
          - user-admin
          - data-admin
          - read-write
          - read
          - write
          - read-write-udf
          - sys-admin
          - udf-admin
  operatorClientCert:
    secretCertSource:
      secretName: aerospike-tls
      caCertsFilename: ca.aerospike.com.pem
      clientCertFilename: asd.aerospike.com.pem
      clientKeyFilename: asd.aerospike.com.key

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security: {}
    network:
      service:
        #        port: 3000
        tls-name: asd.aerospike.com
        tls-authenticate-client: "false"
        tls-port: 4333
      fabric:
        #        port: 3001
        tls-name: asd.aerospike.com
        tls-port: 3012
      heartbeat:
        #        port: 3002
        tls-name: asd.aerospike.com
        tls-port: 3011
      tls:
        - name: asd.aerospike.com
          cert-file: /etc/aerospike/ssl/asd.aerospike.com.pem
          key-file: /etc/aerospike/ssl/asd.aerospike.com.key
          ca-file: /etc/aerospike/ssl/ca.aerospike.com.pem
    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /test/dev/xvdf
      - name: avs-index
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /avs-index/dev/xvdf
      - name: avs-data
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /avs-data/dev/xvdf
      - name: avs-meta
        nsup-period: 600
        nsup-threads: 2
        evict-tenths-pct: 5
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /avs-meta/dev/xvdf