replicaCount: 3
proximusConfig:
  heartbeat:
    seeds:
      - address: proximus-gke-aerospike-proximus-0.proximus-gke-aerospike-proximus.proximus.svc.cluster.local 
        port: 5001
      - address: proximus-gke-aerospike-proximus-1.proximus-gke-aerospike-proximus.proximus.svc.cluster.local 
        port: 5001
      - address: proximus-gke-aerospike-proximus-2.proximus-gke-aerospike-proximus.proximus.svc.cluster.local 
        port: 5001

  interconnect:
    ports:
      5001:
        addresses:
          0.0.0.0
  aerospike:
    metadata-namespace: "proximus-meta"
    seeds:
      - aerocluster-0-0.aerocluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    #    file: /var/log/aerospike-proximus/aerospike-proximus.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: info
      root: info
      com.aerospike.vector.embedded.client: debug
    ticker-interval: 10

service:
  enabled: true
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  ports:
    - name: "svc-port"
      port: 5000
      targetPort: 5000

# schedule proximus nodes
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: aerospike.com/node-pool
            operator: In
            values:
            - "proximus"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - "aerospike-proximus"
